### ISSUE TITLE
Error: [vuex] do not mutate vuex store state outside mutation handlers 

### ISSUE THREAD

**Issue by Camil88** [stagerightlabs/Vue-Three-Demo#5]
Hello, I've followed your tutorial thoroughly  and wrote similar app in Vue3. The issue is that when I run the app then the following error shows up:

`
Error: [vuex] do not mutate vuex store state outside mutation handlers 
`

I haven't seen anywhere in your code where you mutate state outside mutation handlers. That's why I don't get it. Has it something to do with Vue3 version? 

Extra question: is it possible that you upgrade your code and check if everything work fine in Vue3? I would highly appreciate it.

**Comment by rydurham** [comment]
Hello! Thanks for reaching out.  My guess is that the problem you are seeing is likely due to some difference with Vue 3, but I am not positive about that.  I haven't seen that error in my Vue2 version, but that does not mean there are no bugs there to be reckoned with.

It has been on my list to upgrade this project to Vue 3 for some time, but my workload is such that I am not able to give this much priority at the moment.  Hopefully someday I will have the time to work through the upgrade.

**Comment by Camil88** [comment]
Ok, thank you for your answer.

**Comment by rydurham** [comment]
Thank you!  I appreciate it.

**Comment by rydurham** [comment]
Thank you for your help in looking into this problem.   I have now attempted an upgrade to Vue3 in PR #6, making use of the technique discussed in your SO post.   So far it seems to be working well.  I am going to close this issue for now but feel free to reopen if you would like.
